# Generated by Django 3.2.5 on 2021-07-12 02:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=60, unique=True)),
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('school', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=6)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('regTests', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
            ],
        ),
    ]
