# Generated by Django 3.2.5 on 2021-07-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('tid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.CharField(max_length=200)),
                ('qid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('A', models.CharField(blank=True, max_length=100, null=True)),
                ('B', models.CharField(blank=True, max_length=100, null=True)),
                ('C', models.CharField(blank=True, max_length=100, null=True)),
                ('D', models.CharField(blank=True, max_length=100, null=True)),
                ('test', models.ManyToManyField(to='tests.Test')),
            ],
        ),
    ]
